{
    "system_prompt": "You are a large language model named Athena and you are a personal assistant and companion to your user Kevin. Keep your responses short and simple and less than three sentences.",
    "adult_prompt": "You are a large language model named Athena and you are a personal companion to your user Kevin. You will speak with a flirty tone and keep track of your last response in order to keep the flow of the conversation.",
    "translate_prompt": "Translate to {language} only. Do not respond only translate the user prompt.",
    "enable_thinking": false,
    "adult_thinking": false,
    "think_trigger_phrase": "think",
    "streaming": true,
    "headset_alsa_pattern": "Composite Device",
    "external_alsa_pattern": "UACDemoV1",
    "path_b_force_external_device": true,
    "translate_lock_consecutive": 2,
    "tts_max_chars_per_chunk": 300,
    "voice_options": {
        "sky":     "af_sky",
        "heart":   "af_heart",
        "bella":   "af_bella",
        "nicole":  "af_nicole",
        "michael": "am_michael",
        "puck":    "am_puck",
        "fenrir":  "am_fenrir",
        "emma":    "bf_emma",
        "fable":   "bm_fable"
    },
    "speed_grid": [0.68, 0.76, 0.84, 0.92, 1.00, 1.08, 1.16, 1.24, 1.32],
    "path_b_voice_table": {
        "spanish":     {"lang": "es",    "female": "ef_dora",     "male": "em_alex",    "bucket": "spanish"},
        "tagalog":     {"lang": "es",    "female": "ef_dora",     "male": "em_alex",    "bucket": "spanish"},
        "indonesian":  {"lang": "es",    "female": "ef_dora",     "male": "em_alex",    "bucket": "spanish"},
        "malay":       {"lang": "es",    "female": "ef_dora",     "male": "em_alex",    "bucket": "spanish"},
        "catalan":     {"lang": "es",    "female": "ef_dora",     "male": "em_alex",    "bucket": "spanish"},
        "italian":     {"lang": "it",    "female": "if_sara",     "male": "im_nicola",  "bucket": "italian"},
        "romanian":    {"lang": "it",    "female": "if_sara",     "male": "im_nicola",  "bucket": "italian"},
        "latin":       {"lang": "it",    "female": "if_sara",     "male": "im_nicola",  "bucket": "italian"},
        "maltese":     {"lang": "it",    "female": "if_sara",     "male": "im_nicola",  "bucket": "italian"},
        "portuguese":  {"lang": "pt-br", "female": "pf_dora",     "male": "pm_alex",    "bucket": "portuguese"},
        "galician":    {"lang": "pt-br", "female": "pf_dora",     "male": "pm_alex",    "bucket": "portuguese"},
        "french":      {"lang": "fr-fr", "female": "ff_siwis",    "male": "em_alex",    "bucket": "french"},
        "haitian":     {"lang": "fr-fr", "female": "ff_siwis",    "male": "em_alex",    "bucket": "french"},
        "occitan":     {"lang": "fr-fr", "female": "ff_siwis",    "male": "em_alex",    "bucket": "french"},
        "breton":      {"lang": "fr-fr", "female": "ff_siwis",    "male": "em_alex",    "bucket": "french"},
        "hindi":       {"lang": "en-us", "female": "af_heart",    "male": "am_michael", "bucket": "hindi"},
        "urdu":        {"lang": "en-us", "female": "af_heart",    "male": "am_michael", "bucket": "hindi"},
        "bengali":     {"lang": "en-us", "female": "af_heart",    "male": "am_michael", "bucket": "hindi"},
        "punjabi":     {"lang": "en-us", "female": "af_heart",    "male": "am_michael", "bucket": "hindi"},
        "marathi":     {"lang": "en-us", "female": "af_heart",    "male": "am_michael", "bucket": "hindi"},
        "gujarati":    {"lang": "en-us", "female": "af_heart",    "male": "am_michael", "bucket": "hindi"},
        "nepali":      {"lang": "en-us", "female": "af_heart",    "male": "am_michael", "bucket": "hindi"},
        "sanskrit":    {"lang": "en-us", "female": "af_heart",    "male": "am_michael", "bucket": "hindi"},
        "sinhala":     {"lang": "en-us", "female": "af_heart",    "male": "am_michael", "bucket": "hindi"},
        "sindhi":      {"lang": "en-us", "female": "af_heart",    "male": "am_michael", "bucket": "hindi"},
        "assamese":    {"lang": "en-us", "female": "af_heart",    "male": "am_michael", "bucket": "hindi"},
        "persian":     {"lang": "en-us", "female": "af_heart",    "male": "am_michael", "bucket": "hindi"},
        "pashto":      {"lang": "en-us", "female": "af_heart",    "male": "am_michael", "bucket": "hindi"},
        "tajik":       {"lang": "en-us", "female": "af_heart",    "male": "am_michael", "bucket": "hindi"},
        "tamil":       {"lang": "en-us", "female": "af_heart",    "male": "am_michael", "bucket": "hindi"},
        "telugu":      {"lang": "en-us", "female": "af_heart",    "male": "am_michael", "bucket": "hindi"},
        "kannada":     {"lang": "en-us", "female": "af_heart",    "male": "am_michael", "bucket": "hindi"},
        "malayalam":   {"lang": "en-us", "female": "af_heart",    "male": "am_michael", "bucket": "hindi"},
        "japanese":    {"lang": "en-us", "female": "af_heart",    "male": "am_michael", "bucket": "japanese"},
        "korean":      {"lang": "en-us", "female": "af_heart",    "male": "am_michael", "bucket": "japanese"},
        "chinese":     {"lang": "en-us", "female": "af_heart",    "male": "am_michael", "bucket": "chinese"},
        "vietnamese":  {"lang": "en-us", "female": "af_heart",    "male": "am_michael", "bucket": "chinese"},
        "thai":        {"lang": "en-us", "female": "af_heart",    "male": "am_michael", "bucket": "chinese"},
        "lao":         {"lang": "en-us", "female": "af_heart",    "male": "am_michael", "bucket": "chinese"},
        "burmese":     {"lang": "en-us", "female": "af_heart",    "male": "am_michael", "bucket": "chinese"},
        "khmer":       {"lang": "en-us", "female": "af_heart",    "male": "am_michael", "bucket": "chinese"},
        "tibetan":     {"lang": "en-us", "female": "af_heart",    "male": "am_michael", "bucket": "chinese"},
        "_fallback":   {"lang": "en-us", "female": "af_sky",      "male": "am_michael", "bucket": "fallback"}
    },
    "translation_voice_gender_default": "male",
    "temperature": 1.0,
    "top_p": 0.95,
    "top_k": 64,
    "n_ctx": 4096,
    "n_gpu_layers": 99,
    "n_batch": 128
}
